const players = [
    {
        id: 1,
        nick: "KSCERATO",
        nome: "Kaike Cerato",
        time: "FURIA",
        funcao: "Rifler",
        nacionalidade: "BR",
        ranking_hltv: 7,
    },
    {
        id: 2,
        nick: "biguzera",
        nome: "Rodrigo Bittencourt",
        time: "paiN Gaming",
        funcao: "IGL/Rifler",
        nacionalidade: "BR",
        ranking_hltv: 10,
    },
    {
        id: 3,
        nick: "skullz",
        nome: "Matheus Santos",
        time: "Legacy",
        funcao: "Rifler",
        nacionalidade: "BR",
        ranking_hltv: 16,
    },
    {
        id: 4,
        nick: "insani",
        nome: "Matheus Quirino",
        time: "MIBR",
        funcao: "Rifler",
        nacionalidade: "BR",
        ranking_hltv: 18,
    },
    {
        id: 5,
        nick: "SHOOWTiME",
        nome: "Gustavo Gonçalves",
        time: "Imperial",
        funcao: "Support/Rifler",
        nacionalidade: "BR",
        ranking_hltv: 38,
    },
    {
        id: 6,
        nick: "Lucaozy",
        nome: "Lucas Neves",
        time: "Fluxo",
        funcao: "Rifler",
        nacionalidade: "BR",
        ranking_hltv: 39,
    },
    {
        id: 7,
        nick: "KNCB",
        nome: "Kenji Cabrera",
        time: "Sharks",
        funcao: "AWPer",
        nacionalidade: "UY",
        ranking_hltv: 48,
    },
    {
        id: 8,
        nick: "kauez",
        nome: "Kauez Pereira",
        time: "RED Canids",
        funcao: "Entry/Support",
        nacionalidade: "BR",
        ranking_hltv: 55,
    },
    {
        id: 9,
        nick: "snow",
        nome: "João Vinicius",
        time: "paiN Gaming",
        funcao: "Rifler",
        nacionalidade: "BR",
        ranking_hltv: 10,
    },
    {
        id: 10,
        nick: "FalleN",
        nome: "Gabriel Toledo",
        time: "FURIA",
        funcao: "AWPer/IGL",
        nacionalidade: "BR",
        ranking_hltv: 7,
    },
    {
        id: 11,
        nick: "NiKo",
        nome: "Nikola Kovač",
        nacionalidade: "BA",
        time: "G2",
        funcao: "Rifler",
    },
    {
        id: 12,
        nick: "electroNic",
        nome: "Denis Sharipov",
        nacionalidade: "RU",
        time: "Virtus.pro",
        funcao: "Rifler/IGL",
    },
    {
        id: 13,
        nick: "SunPayus",
        nome: "Alvaro Garcia",
        nacionalidade: "ES",
        time: "G2",
        funcao: "AWPer",
    },
    {
        id: 14,
        nick: "Spinx",
        nome: "Lotan Giladi",
        nacionalidade: "IL",
        time: "Vitality",
        funcao: "Rifler",
    },
    {
        id: 15,
        nick: "ropz",
        nome: "Robin Kool",
        nacionalidade: "EE",
        time: "Vitality",
        funcao: "Rifler",
    },
    {
        id: 16,
        nick: "torzsi",
        nome: "Ádám Torzsás",
        nacionalidade: "HU",
        time: "MOUZ",
        funcao: "AWPer",
    },
    {
        id: 17,
        nick: "xertioN",
        nome: "Dorian Berman",
        nacionalidade: "IL",
        time: "MOUZ",
        funcao: "Entry",
    },
    {
        id: 18,
        nick: "Jimpphat",
        nome: "Jimi Salo",
        nacionalidade: "FI",
        time: "MOUZ",
        funcao: "Rifler",
    },
    {
        id: 19,
        nick: "b1t",
        nome: "Valeriy Vakhovskiy",
        nacionalidade: "UA",
        time: "NAVI",
        funcao: "Rifler",
    },
    {
        id: 20,
        nick: "Aleksib",
        nome: "Aleksi Virolainen",
        nacionalidade: "FI",
        time: "NAVI",
        funcao: "IGL",
    },
    {
        id: 21,
        nick: "ZywOo",
        nome: "Mathieu Herbaut",
        nacionalidade: "FR",
        time: "Vitality",
        funcao: "AWPer",
    },
    {
        id: 22,
        nick: "blameF",
        nome: "Benjamin Bremer",
        nacionalidade: "DK",
        time: "Astralis",
        funcao: "Rifler/IGL",
    },
    {
        id: 23,
        nick: "device",
        nome: "Nicolai Reedtz",
        nacionalidade: "DK",
        time: "Astralis",
        funcao: "AWPer",
    },
    {
        id: 24,
        nick: "hades",
        nome: "Aleksander Zawistowski",
        nacionalidade: "PL",
        time: "9INE",
        funcao: "AWPer",
    },
    {
        id: 25,
        nick: "frozen",
        nome: "David Čerňanský",
        nacionalidade: "SK",
        time: "FaZe",
        funcao: "Rifler",
    },
    {
        id: 26,
        nick: "Twistzz",
        nome: "Russel Van Dulken",
        nacionalidade: "CA",
        time: "FaZe",
        funcao: "Rifler",
    },
    {
        id: 27,
        nick: "rain",
        nome: "Håvard Nygaard",
        nacionalidade: "NO",
        time: "FaZe",
        funcao: "Entry",
    },
    {
        id: 28,
        nick: "Perfecto",
        nome: "Ilya Zalutskiy",
        nacionalidade: "RU",
        time: "Cloud9",
        funcao: "Support",
    },
    {
        id: 29,
        nick: "sh1ro",
        nome: "Dmitry Sokolov",
        nacionalidade: "RU",
        time: "Cloud9",
        funcao: "AWPer",
    },
    {
        id: 30,
        nick: "flameZ",
        nome: "Shahar Shushan",
        nacionalidade: "IL",
        time: "Vitality",
        funcao: "Entry",
    }
];

export default { players };
